/**
 * Typed API helpers — reads from the static /data.json file generated by the backend pipeline.
 */

import fs from 'fs/promises';
import path from 'path';
import { unstable_noStore as noStore } from 'next/cache';
import type { AiPrediction, SignalTrend } from './types';

// ── Types ──────────────────────────────────────────────────────────────────────

export interface SignalDetail {
  factor_id: string;
  name: string;
  score: number | null;
  raw_value: number | null;
  velocity_4wk: number | null;
  velocity_12wk: number | null;
  stale: boolean;
  error_message: string | null;
  weight_used: number | null;
}

export interface ConfidenceInterval {
  lower: number | null;
  upper: number | null;
  std_dev: number | null;
  degradation_multiplier: number | null;
  confidence_level: string;
}

export interface AnalogMatch {
  episode_name: string;
  week_matched: string;
  similarity: number;
  weeks_to_peak: number | null;
  max_drawdown_pct: number | null;
}

export interface LatestScores {
  run_id: string;
  run_date: string;
  composite_score: number;
  confidence_interval: ConfidenceInterval;
  correlation_penalty: number;
  quality_verdict: "GREEN" | "YELLOW" | "RED";
  low_confidence: boolean;
  stale_signals: string[];
  weights_used: Record<string, number>;
  signals: SignalDetail[];
  analogs: {
    bubble_analogs: AnalogMatch[];
    boom_analogs: AnalogMatch[];
    adjusted_risk: string;
    adjustment_reason: string;
  };
  aiPredictions?: Record<string, AiPrediction>;
}

export interface HistoryEntry {
  run_date: string;
  composite_score: number;
  composite_lower: number | null;
  composite_upper: number | null;
  quality_verdict: "GREEN" | "YELLOW" | "RED" | null;
  signals: Record<string, number | null>;
  aiPredictions?: Record<string, AiPrediction>;
}

export interface HistoryResponse {
  data: HistoryEntry[];
}

// ── Fetch helpers ─────────────────────────────────────────────────────────────

async function fetchJson(): Promise<LatestScores[]> {
  if (process.env.NODE_ENV === 'development') {
    noStore();
  }
  try {
    const filePath = path.join(process.cwd(), 'public', 'data.json');
    const fileContents = await fs.readFile(filePath, 'utf8');
    return JSON.parse(fileContents);
  } catch (e) {
    return [];
  }
}

export async function fetchLatestScores(): Promise<LatestScores | null> {
  const data = await fetchJson();
  if (!data || data.length === 0) return null;
  return data[data.length - 1];
}

export async function fetchHistory(weeks = 52): Promise<HistoryResponse> {
  const data = await fetchJson();
  const recent = data.slice(-weeks);
  const formatted = recent.map(entry => {
     const signalsMap: Record<string, number | null> = {};
     entry.signals?.forEach(s => {
       signalsMap[s.factor_id] = s.score;
     });
     
     return {
       run_date: entry.run_date,
       composite_score: entry.composite_score,
       composite_lower: entry.confidence_interval?.lower ?? null,
       composite_upper: entry.confidence_interval?.upper ?? null,
       quality_verdict: entry.quality_verdict,
       signals: signalsMap,
       aiPredictions: entry.aiPredictions
     };
  });
  return { data: formatted };
}

export async function fetchSignalHistory(factorId: string, weeks = 52) {
  const data = await fetchJson();
  const recent = data.slice(-weeks);
  const formatted = recent.map(entry => {
    const sig = entry.signals?.find(s => s.factor_id === factorId);
    return {
      run_date: entry.run_date,
      score: sig ? sig.score : null,
      raw_value: sig ? sig.raw_value : null
    };
  });
  return { data: formatted };
}

export interface HistoryContext {
  /** Number of readings recorded so far — the pool every score is ranked against. */
  readings: number;
  /** ISO date of the first reading, or null when there is no history. */
  since: string | null;
  /** Score movement per signal vs. roughly a month ago (null when history is too short). */
  trends: Record<string, SignalTrend | null>;
}

const DAY_MS = 24 * 60 * 60 * 1000;
const TREND_LOOKBACK_DAYS = 28;
const TREND_MIN_DAYS = 5;

/**
 * Compares the latest reading with the one closest to four weeks earlier. If the
 * history is shorter than that, falls back to the oldest reading — and reports no
 * trend at all when even that is under TREND_MIN_DAYS old.
 *
 * Computed from the stored scores rather than the pipeline's `velocity_4wk`, which
 * counts runs (not weeks) and so means "4 days" now that the pipeline runs daily.
 */
export async function fetchHistoryContext(): Promise<HistoryContext> {
  const data = await fetchJson();
  if (!data || data.length === 0) return { readings: 0, since: null, trends: {} };

  const sorted = [...data].sort((a, b) => a.run_date.localeCompare(b.run_date));
  const latest = sorted[sorted.length - 1];
  const latestMs = Date.parse(latest.run_date);

  const cutoffMs = latestMs - TREND_LOOKBACK_DAYS * DAY_MS;
  const onOrBeforeCutoff = sorted.filter((e) => Date.parse(e.run_date) <= cutoffMs);
  const baseline = onOrBeforeCutoff.length > 0 ? onOrBeforeCutoff[onOrBeforeCutoff.length - 1] : sorted[0];
  const daysAgo = Math.round((latestMs - Date.parse(baseline.run_date)) / DAY_MS);

  const trends: Record<string, SignalTrend | null> = {};
  for (const s of latest.signals ?? []) {
    const before = baseline.signals?.find((b) => b.factor_id === s.factor_id)?.score;
    trends[s.factor_id] =
      daysAgo >= TREND_MIN_DAYS && s.score != null && before != null
        ? { delta: s.score - before, daysAgo }
        : null;
  }

  return { readings: sorted.length, since: sorted[0].run_date, trends };
}

export async function fetchAnalogs() {
  const data = await fetchJson();
  if (!data || data.length === 0) return null;
  return data[data.length - 1].analogs;
}

export async function fetchHealth() {
  return { status: "ok" };
}
