/**
 * Typed API helpers — reads from the static /data.json file generated by the backend pipeline.
 */

import fs from 'fs/promises';
import path from 'path';
import { unstable_noStore as noStore } from 'next/cache';
import type { AiPrediction } from './types';

// ── Types ──────────────────────────────────────────────────────────────────────

export interface SignalDetail {
  factor_id: string;
  name: string;
  score: number | null;
  raw_value: number | null;
  velocity_4wk: number | null;
  velocity_12wk: number | null;
  stale: boolean;
  error_message: string | null;
  weight_used: number | null;
}

export interface ConfidenceInterval {
  lower: number | null;
  upper: number | null;
  std_dev: number | null;
  degradation_multiplier: number | null;
  confidence_level: string;
}

export interface AnalogMatch {
  episode_name: string;
  similarity: number;
  weeks_to_peak: number | null;
  max_drawdown_pct: number | null;
}

export interface LatestScores {
  run_id: string;
  run_date: string;
  composite_score: number;
  confidence_interval: ConfidenceInterval;
  correlation_penalty: number;
  quality_verdict: "GREEN" | "YELLOW" | "RED";
  low_confidence: boolean;
  stale_signals: string[];
  weights_used: Record<string, number>;
  signals: SignalDetail[];
  analogs: {
    bubble: AnalogMatch[];
    boom: AnalogMatch[];
    adjusted_risk: string;
    adjustment_reason: string;
  };
  aiPredictions?: Record<string, AiPrediction>;
}

export interface HistoryEntry {
  run_date: string;
  composite_score: number;
  composite_lower: number | null;
  composite_upper: number | null;
  quality_verdict: "GREEN" | "YELLOW" | "RED" | null;
  signals: Record<string, number | null>;
  aiPredictions?: Record<string, AiPrediction>;
}

export interface HistoryResponse {
  data: HistoryEntry[];
}

// ── Fetch helpers ─────────────────────────────────────────────────────────────

async function fetchJson(): Promise<LatestScores[]> {
  if (process.env.NODE_ENV === 'development') {
    noStore();
  }
  try {
    const filePath = path.join(process.cwd(), 'public', 'data.json');
    const fileContents = await fs.readFile(filePath, 'utf8');
    return JSON.parse(fileContents);
  } catch (e) {
    return [];
  }
}

export async function fetchLatestScores(): Promise<LatestScores | null> {
  const data = await fetchJson();
  if (!data || data.length === 0) return null;
  return data[data.length - 1];
}

export async function fetchHistory(weeks = 52): Promise<HistoryResponse> {
  const data = await fetchJson();
  const recent = data.slice(-weeks);
  const formatted = recent.map(entry => {
     const signalsMap: Record<string, number | null> = {};
     entry.signals?.forEach(s => {
       signalsMap[s.factor_id] = s.score;
     });
     
     return {
       run_date: entry.run_date,
       composite_score: entry.composite_score,
       composite_lower: entry.confidence_interval?.lower ?? null,
       composite_upper: entry.confidence_interval?.upper ?? null,
       quality_verdict: entry.quality_verdict,
       signals: signalsMap,
       aiPredictions: entry.aiPredictions
     };
  });
  return { data: formatted };
}

export async function fetchSignalHistory(factorId: string, weeks = 52) {
  const data = await fetchJson();
  const recent = data.slice(-weeks);
  const formatted = recent.map(entry => {
    const sig = entry.signals?.find(s => s.factor_id === factorId);
    return {
      run_date: entry.run_date,
      score: sig ? sig.score : null,
      raw_value: sig ? sig.raw_value : null
    };
  });
  return { data: formatted };
}

export async function fetchAnalogs() {
  const data = await fetchJson();
  if (!data || data.length === 0) return null;
  return data[data.length - 1].analogs;
}

export async function fetchHealth() {
  return { status: "ok" };
}
